name: Dushyant Agarwal
description: Blogging about stuffs
meta_description: "Ruby on Rails, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://dagarwal.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://dagarwal.com'
author:         'Dushyant'
